### ISSUE TITLE
multihop example hangs occasionally

### ISSUE THREAD

**Issue by jtsiva** [jtsiva/ComLocAL#12]
It appears that somewhere during one of the stop() calls, the program hangs every once and a while.

Maybe there is a blocking read that I haven't found yet?
Race condition?

**Comment by jtsiva** [comment]
This might be related. I ran the multihop example on the sender side with:
`sudo python multihop.py -r sender -c 325 -d .01`
and got the following exception:
`Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/ComLocAL/comlocal/core/Com.py", line 81, in _procWrite
    while self._threadsRunning:
TypeError: 'bool' object does not support item deletion`

And from time stamp in log it looks like routing table updates were still being recorded.

**Comment by jtsiva** [comment]
Hangs pretty consistently on my laptop, but there is no error message.

**Comment by jtsiva** [comment]
Hanging again, but in getNbCmd.py, so it still looks like something wrong with the stop function in Com maybe...

**Comment by jtsiva** [comment]
The hang is caused by the Bluetooth stop function. In particular:
`err = self._bluez.hci_le_set_scan_enable(
		    self._sock.fileno(),
		    0,  # 1 - turn on;  0 - turn off
		    0, # 0-filtering disabled, 1-filter out duplicates
		    5000  # timeout
		)`
will sometimes timeout or just hang indefinitely. I need to stop scanning or else it screws up the bluetooth...

**Comment by jtsiva** [comment]
PR #15 fixes this by using hcitool directly to start/stop scanning.
